### ISSUE TITLE
Windows install instructions

### ISSUE THREAD

**Issue by mtchem** [girldevelopit/gdi-website#157]
There are no instructions for people with windows to both install ruby on rails and how to use the git hub clone.

**Comment by mtchem** [comment]
This is what I have so far, but there are still issues.
1. GitHub
  1. Sign-up for GitHub and log-in
b.	Go to https://github.com/girldevelopit/gdi-new-site
c.	Fork the site (button on top right corner), This with create a copy on your github site
d.	Clone your new copy by clicking the “Clone in Desktop” button.  A window will pop up asking where you want to save it (save it wherever you want, I saved it into the Sites folder, which is the default folder, just remember the path to the folder.)
e.	Go to the command window and change the command line path to the folder where you have the gdi-new-site
    i. You do this by typing first typing “cd” then the path to your file (i.e. > cd \Sites\gdi-new-site)
f.	Type bundle install
i.	If you get the error “An error occurred while installing CFPropertyList –v blah, blah, blah” don’t worry we can fix it
1.	Open windows explorer and open the gdi-new-site folder (it should be in the Sites folder, or wherever you saved the clone in step 1d)
2.	Open the GemFile in a code editor(if you don’t have a code editor, go to step 2. Optional for instructions on how to install Atom.
3.	Change “source ‘https://rubygems.org’ “ to “source ‘http://rubygems.org” and SAVE the file
4.	Go back to the command window and type bundle install
	

2. Optional: if you don’t have it already download a code editor that works with Ruby
   a. Atom ( https://atom.io/ ) is a free code editor that works with Ruby and GitHub.
b.	Click to download windows installer
c.	If the installer does not automatically start than click on the downloaded AtomSetup.exe 
d.	Follow the setup wizard
e.	Open Atom C:\Sites\gdi-new-site, change .ruby-version to 2.1.2  and Gemfile #ruby  ”2.1.2”
f.	
3.	Download Ruby on Rails
a.	Go to http://railsinstaller.org/en
b.	Scroll down and click on the download button that is appropriate for your machine
c.	If the installer does not automatically start than click on the downloaded .exe file (it should look like railsinstaller-3.1.0.exe)
d.	Follow the setup wizard (make sure the “Configure git and ssh when installation has completed” box is checked
e.	A command line box will pop up
    i.Change the command line path to the folder where you have the Gem file (this is the same place where you saved the clone)
1.	You do this by typing first typing “cd” then the path to your file
2.	i.e. > cd \Sites 
3.	i.e. > cd \Sites\app

    ii. type install bundle
1.	If the install bundle works, a bunch of text should pop up and the last line should say “nothing to do! Yay!”
2.	If the install bundle doesn’t work and you  have an error message saying it can’t get the information from <https://rubygems.org/gems/rake... blah blah blah , then you need to hack the Gem file

4.	Hack the Gem file
   a. Go to the folder where you saved (i.e. C:\Sites\Gemfile) and open it in your code editor (like Atom)
b.	Change source 'https://rubygems.org' to source 'http://rubygems.org'
c.	Save the file
d.	Go back to the command line and type install bundle

You should now have all the dependencies for your project done

**Comment by Roenok** [comment]
Going to try a Windows install tonight, so I'll see about some docs as well.

**Comment by Roenok** [comment]
@kstack7 No idea! I'll find out tonight. I suspect it is the part highlighted in red.

**Comment by kstack7** [comment]
Taking Kristi's lead in Slack by downloading Vagrant to try out the Windows route.

**Comment by Roenok** [comment]
General note: Native Windows install currently appears to be impossible due to Unix-only gems. See #174 for more. Windows users may be able to use a virtual machine with Linux.

**Comment by juliaelman** [comment]
@Roenok were you able to check out these docs and test? Wanting to see if we can add platform specific instructions + Windows would be awesome sauce.

**Comment by Roenok** [comment]
@juliaelman Windows install is currently impossible, pending resolution of https://github.com/girldevelopit/gdi-new-site/issues/174

**Comment by kstack7** [comment]
Pending latest build changes to support Windows. Please checkout http://girl-develop-it-staging.herokuapp.com/ and #371 for details & keep an eye out for bugs!

**Comment by Roenok** [comment]
We can close this one, as Windows users can use Vagrant
