### ISSUE TITLE
LinkedIn links are incorrect 

### ISSUE THREAD

**Issue by therufs** [girldevelopit/gdi-website#290]
_Description_
At least some chapters have incorrect LinkedIn links, e.g.: https://www.linkedin.com/https://www.linkedin.com/groups/Girl-Develop-It-Boise-6696817 

I suspect this is a problem for bios too. 

_Ask_
From views/chapters/_social_media_chapter.html.erb: 

``` erb
21     <%= link_to "https://www.linkedin.com/#{user.linkedin}" do %>
```
# {user.linkedin} is already a complete URL (at least for some chapters) so we end up with malformed links.

_To Do_ (edited 5/11)
- [ ] Write helper method to sanitize links for chapters and bios.
- [ ] Update erb accordingly.

**Comment by therufs** [comment]
I'm happy to do the erb tweaks if someone with admin access on the site can let me know what we standardized to :) \o/

**Comment by Roenok** [comment]
@therufs I'll take a look. I think right now individuals should just be username and chapters should be group name.

**Comment by juliaelman** [comment]
@Roenok going to assign this to you while you determine how to move forward. Please switch the assignee to @therufs once you know how best to move forward.

**Comment by kstack7** [comment]
What's the status of this issue?

**Comment by therufs** [comment]
I haven't looked at it since it originally came up, but am willing to take a crack at it.  Maybe I can write a ~helper method~ to just check the thing we're trying to link to? 

ETA: I was just reminded that I'm supposed to be moving this week O.O Still glad to tackle this and have set a gcal event to remind me to look at it on Monday 5/11 (if I don't get sick of boxes and take a crack at it before then.)

**Comment by kstack7** [comment]
@therufs thanks for the help! I'm nudging a few of these stagnant issues along so we can either wrap 'em up or wipe 'em off the list :)

ooOoo moving, huh? minor detail ;) hope it goes smoothly!!

**Comment by therufs** [comment]
Well I'm not done moving, but I'm having a go at it anyway :D (too dark to haul boxes right now anyway)

**Comment by kstack7** [comment]
yay @therufs! let us know what ya find :)

**Comment by kexline4710** [comment]
I'd be happy to jump on this issue. I did a little bit of tinkering and there are a few options that we have:

1.) **Create a helper that extracts the subpath from a chapter link and tack it onto the intended path.**

[The helper may look something like this](https://github.com/girldevelopit/gdi-new-site/compare/production...kexline4710:bugfix/social_links) and the view would use the helper like this:

``` erb
<%= link_to "https://www.facebook.com/#{format_links(user.fb, "facebook.com")}" do %>
```

**PROS**: Ensures that the link in the db matches the intended host.
**CONS**: Clunky view implementation. Could create some funky links which is a similar problem as the original issue.

2.) **Take a host and the given link in the db and format the entire url path.**

``` rb
def format_links(link, host)
  link_host_match = link.match(/\.com\/(.*)/)
  sub_path = link_host_match ? link_host_match[1] : ""
  "https://www.#{host}/#{sub_path}".html_safe
end
```

``` erb
<%= link_to format_links(user.fb, "facebook.com") do %>
```

**PROS**: Encapsulates logic for format link. Clean implementation in view.
**CONS**: Crude and unreliable regex matching. Returns the main host page if the link in the db doesn't match given host. (bad if that's not what we want, good if it is)

3.) **Trust the link in the db, but ensure it is html safe.**

``` erb
<%= link_to user.fb.html_safe do %>
```

_Note: These are some of the edge cases that I think are worth considering that any implementation should at least take into consideration_

**PROS**: Clean implementation. Encourages link validation to happen at model/db level.
**CONS**: No check on whether it is intended host. Potentially too trustworthy without additional validation.

Open to thoughts and feedback.

**Comment by paulhenrich** [comment]
Just a heads-up about a counter-intuitive method in rails that trips a lot of folks up. `#html_safe`, somewhat confusingly, doesn't make anything safe (in fact, it can be dangerous). It tells the view that you are vouching for the content that it _is_ safe (that is, already escaped or not from a user). 

If you want more details, this is a pretty good write-up: [Stay safe while using html_safe in rails](http://product.reverb.com/2015/08/29/stay-safe-while-using-html_safe-in-rails/)

Aside from that, if you want to do something like 2, check out [URI](http://ruby-doc.org/stdlib-2.1.1/libdoc/uri/rdoc/URI.html) from the standard library. It may make parsing / putting together URLs in your helper cleaner and more predictable.

**Comment by kexline4710** [comment]
Ah! Thanks for the feedback. I'll take a look.

I'm comfortable with the URI library, but I think the question I have in mind is where in the experience do we want to "validate" the link. I now think that I was being too fancy in trying to ensure that the link in the db matches the social link, when I think that's unnecessary. If an icon is linked to the wrong link, then the record should be fixed.

**Comment by paulhenrich** [comment]
No problem. That sounds like a good approach. You could fix links with a data migration or rake task that runs a heuristic like you've described against the existing data. One option would be to change things around so that you just require and use the full URL (which you could validate with a custom `validate :linked_in_link` method in the model)
