### ISSUE TITLE
on clicking nav bar sponsors the header sponsors should be at the top of the page

### ISSUE THREAD

**Issue by pshegde** [girldevelopit/gdi-website#309]
**Description**
On clicking materials the materials header is at the top of the page. However, on clicking sponsors and donate the header is not at the top of the page. 

**Ask**
1) adding a SUPPORTERS header at the top of this page, 
2) changing the navigation link label to SUPPORTERS
(Edited based on comments below by @DBNess and @kstack7 )

**To Do**
Same as above

**Additional Info**
![untitled](https://cloud.githubusercontent.com/assets/1585470/7103800/19730ea8-e06e-11e4-9ad7-eaa7e0938d6d.png)

**Comment by kstack7** [comment]
Thank you for this issue and suggestion, @pshegde! Please reference our issue template #83 for future contributions. We'd greatly appreciate it!

I believe the reason for this lacking header is because we also mention our partners lower in the page. I'd love to hear what others think about this layout, too.

**Comment by DBNess** [comment]
Thank you, @pshegde! This is a great suggestion for design consistency -- we should have a header here with words and not just the flourish. I see @kstack7's point re: why Sponsors wouldn't make sense, though, so I wonder if maybe "SUPPORTERS" or "SPONSORS & PARTNERS" something general should be the page header and then we can keep the breakout between Sponsors and Partners down the page. Definitely +1 / :+1: Prajakta's suggestion, just want to figure out wording that makes sense. cc @corinnepw

**Comment by kstack7** [comment]
Hmm yeah I almost wonder if we should swap out the nav for "supporters" so that we can use that as the header and "SPONSORS" / "PARTNERS" as the sub-headers...

**Comment by DBNess** [comment]
@kstack7 "supporters" isn't a convention on non-profit websites quite like "sponsors" is, but it's more accurate, so I'd say :+1: to renaming to Supporters & adding the header we see on the other pages for consistency.

**Comment by DBNess** [comment]
@pshegde could you please reformat this issue to [follow the template here (you can copy & paste the markdown from this link into this issue to edit)](https://github.com/girldevelopit/gdi-new-site/issues/new?body=**Description**%0A*Include%20a%20high%20level%20description%20of%20the%20feature%20or%20error%20here%20including%20steps%20of%20how%20to%20recreate%20if%20applicable.%20Include%20any%20benefits%2C%20challenges%20or%20considerations.%20Can%20be%20short%20and%20sweet.*%0A%0A**Ask**%0A*Describe%20the%20desired%20behavior%20and%20what%20would%20deem%20this%20issue%2Fbug%2Ffeature%20complete.*%0A%0A**To%20Do**%0A-%20%5B%20%5D%20Steps%0A-%20%5B%20%5D%20To%0A-%20%5B%20%5D%20Complete%2FFix%0A%0A**Additional%20Info**%0A*Include%20any%20images%2C%20steps%20to%20recreate%2C%20notes%2C%20emojis%2C%20or%20whatever.*%0A) and request 1) adding a SUPPORTERS header at the top of this page, and 2) changing the navigation link label to SUPPORTERS, when you get the chance? Thank you!

**Comment by kstack7** [comment]
Yea @DBNess my only concern was "supporters" reading as "support" which could clash with "donate" hah but "supporters" does make the most sense out of these options.

**Comment by kstack7** [comment]
K so I'm rerouting the config to support the new "supporters" page in place of "sponsors" but I have not gone as deep as to update all the CSS/class names. How do we feel about that? 

Also, with with or without the flourish? Any designers want to chime in?

Without flourish -- 
![without](https://cloud.githubusercontent.com/assets/6612770/7604055/209d48e6-f90b-11e4-91ae-83d26f2daf26.png)

With flourish -- 
![with](https://cloud.githubusercontent.com/assets/6612770/7604057/230258d8-f90b-11e4-83e3-6fd3ccf62432.png)

**Comment by kstack7** [comment]
Also, I'm assuming we have the /sponsors mentioned elsewhere so I added a redirect for that cause...

**Comment by DBNess** [comment]
Great, Kristen! Good call on the redirect, always good to remain
backwards-compatible. Maybe ship this without CSS class renames, but create
a followup issue for someone to refactor the class names? That way it
happens, but we create an opportunity for someone else to help out and
limit risk by narrowing the scope of changes.

On Wednesday, May 13, 2015, Kristen notifications@github.com wrote:

> Also, I'm assuming we have the /sponsors mentioned elsewhere so I added a
> redirect for that cause...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/girldevelopit/gdi-new-site/issues/309#issuecomment-101515119
> .

## 

Vanessa Hurst
Co-Founder | Girl Develop It http://www.girldevelopit.com | @girldevelopit
http://twitter.com/girldevelopit

Girl Develop It http://girldevelopit.com/ teaches women to code in over
45 cities
CodeMontage http://www.codemontage.com/ empowers coders to change the
world
Women coders break new ground, and stereotypes - TODAY show
http://www.today.com/video/today/53924117

**Comment by kstack7** [comment]
@minamarkham this is the one I'm talking about...

@Cara-Jo any preferences here, too? Not sure if we want to keep that flourish, change the headers of Sponsors/Partners, or something else that's creative. Thoughts?

**Comment by kstack7** [comment]
@DBNess great idea with the scope creep. I'll keep this one simple for now and open the next CSS swapping issue :)

**Comment by minamarkham** [comment]
@kstack7 no flourish :)

**Comment by kstack7** [comment]
Yeah it did seem out of place...but what if we moved it under the paragraph? meh I'm "take it or leave it" either way haha

**Comment by kstack7** [comment]
Up on staging -- https://girl-develop-it-staging.herokuapp.com/supporters

**Comment by ghost** [comment]
Hi , I want to join you people and learn more about coding , If you are free and can help me to understand what you guys are doing ?

**Comment by kstack7** [comment]
Hello @Trisha1212 and welcome to Girl Develop It's website repo! The site is open to the public and we welcome suggestions, ideas, contributions, etc. If you're curious about us as an organization, why not start by checking us out at https://www.girldevelopit.com/about

**Comment by ghost** [comment]
I am excited to learn and develop the skills , i checked with few people who are listed in site they asked my location(India) and skills experience and said we dont work outside US . hence i checked your git hub repository and thought to sync with you . we can have online discussions and learn and share from each other . if you don't mind

**Comment by kstack7** [comment]
Nope! We keep this repo wide open for these reasons :) Feel free to browse more of our existing issues (https://github.com/girldevelopit/gdi-new-site/issues) and jump in!

**Comment by ghost** [comment]
Sure . Thank you
