### ISSUE TITLE
Chapter for san jose not listed on the map

### ISSUE THREAD

**Issue by pshegde** [girldevelopit/gdi-website#311]
Chapter for gdi san jose not listed on the map

**Comment by kstack7** [comment]
Thanks for the issue, @pshegde. Please reference our issue template ( #83 ) for future contributions.

Our chapter leaders are in charge of their chapter presence so we will likely need to reach out again if one of the leaders does not submit a web admin form.

**Comment by kstack7** [comment]
Aaand correction! We do have a submission for San Jose as of a couple days ago. I'll start populating :)

**Comment by kstack7** [comment]
Okay San Jose is on the map! I've alerted the chapter leader to start populating the page. We're all set from here! Thank you!
