### ISSUE TITLE
Chapter for Girl develop for San jose is not in the Chapters list

### ISSUE THREAD

**Issue by khushali9** [girldevelopit/gdi-website#312]
![screen shot 2015-04-11 at 5 31 05 pm](https://cloud.githubusercontent.com/assets/9066304/7103886/b1e37838-e070-11e4-9801-2a320c746dc1.png)

**Comment by kstack7** [comment]
Closing due to duplication. See #311

**Comment by khushali9** [comment]
but that is Map and this is link of Chapters

**Comment by kstack7** [comment]
Yes, it's all related. This new site is database-driven thus if the data is present in the database, it'll show on the map and in the chapter list.

**Comment by kstack7** [comment]
Hey there, @khushali9! Just to follow-up we did have an admin submission from the San Jose chapter so we can get them in the database. Thanks for checking and submitting!

**Comment by khushali9** [comment]
Got it. Thank You @kstack7
