### ISSUE TITLE
Add a CONTRIBUTING.md File

### ISSUE THREAD

**Issue by DBNess** [girldevelopit/gdi-website#318]
**Description**
We have a great issue template, but it's hard to find as a new contributor. If we use GitHub's CONTRIBUTING.md format, users will get a reminder like this when they open a new issue.
![new_issue_ _centerforopenscience_osf_io](https://cloud.githubusercontent.com/assets/226228/7334301/574c204c-eb55-11e4-9597-b5447176d60a.jpg)

**Ask**
Create a CONTRIBUTING.md file with a quicklink to an issue using the awesome template provided by @kexline4710 in #83

**To Do**
- [ ] Add a basic CONTRIBUTING.md file in the root directory of this project
- [x] Write a URL that creates a new GitHub issue with body content from template #83
- [ ] Add a quicklink section to the CONTRIBUTING.md file linking to the URL above
- [ ] Profit :dollar: :moneybag: 

**Additional Info**
Here's a link to an example of an issue template link courtesty of @sloria & Center for Open Science: https://github.com/CenterForOpenScience/OSF.io/issues/new?body=Steps%0A-------%0A1.%20%0A%0AExpected%0A------------%0A%0AActual%0A--------%0A

**Comment by kstack7** [comment]
Not on my home computer with my local installation atm, but here's the new issue link if someone else wants to supply the file...

Link's a little long, but thorough! :+1: 

https://github.com/girldevelopit/gdi-new-site/issues/new?body=**Description**%0A*Include%20a%20high%20level%20description%20of%20the%20feature%20or%20error%20here%20including%20steps%20of%20how%20to%20recreate%20if%20applicable.%20Include%20any%20benefits%2C%20challenges%20or%20considerations.%20Can%20be%20short%20and%20sweet.*%0A%0A**Ask**%0A*Describe%20the%20desired%20behavior%20and%20what%20would%20deem%20this%20issue%2Fbug%2Ffeature%20complete.*%0A%0A**To%20Do**%0A-%20%5B%20%5D%20Steps%0A-%20%5B%20%5D%20To%0A-%20%5B%20%5D%20Complete%2FFix%0A%0A**Additional%20Info**%0A*Include%20any%20images%2C%20steps%20to%20recreate%2C%20notes%2C%20emojis%2C%20or%20whatever.*%0A

**Comment by DBNess** [comment]
NIIICE @kstack7!! :muscle:

**Comment by kstack7** [comment]
Pushed to staging if anyone wants to take a look/review:

https://github.com/girldevelopit/gdi-new-site/blob/staging/CONTRIBUTING.md

**Comment by therufs** [comment]
@kstack7 I did not even understand what was going on with that quicklink when you sent it before, but now I do and it's ~GLORIOUS~ :+1:

**Comment by kstack7** [comment]
haha @therufs fortunately it's way more concise in the actual file!
