### ISSUE TITLE
Increase Involvement 

### ISSUE THREAD

**Issue by pxh1432** [girldevelopit/gdi-website#321]
![image](https://cloud.githubusercontent.com/assets/12114978/7335149/955ede86-eb70-11e4-9a37-b090a881d5e7.png)

**Comment by pxh1432** [comment]
Oh Sorry I missed the template >.<

**Comment by kstack7** [comment]
We appreciate the thorough input, @pxh1432! We are currently in the process of discussing/implementing a similar procedure over in #282 -- feel free to jump in there! I am going to close this issue for now since it covers a variety of existing ones, but thanks so much for the help!
