### ISSUE TITLE
Updating CSS to match "supporters" change

### ISSUE THREAD

**Issue by kstack7** [girldevelopit/gdi-website#328]
**Description**
_We recently changed the word "sponsors" to "supporters" on the website. The page headers and URL reflect the changes, but the CSS within the code does not. We'd like to now focus on making the sponsors -> supporters changes in the views/CSS files for consistency._

**Ask**
_Change all class and CSS instances from "sponsor"-related names to "supporters" as needed._

**To Do**
- [ ] Change "sponsors" classes used in the supporters.html.erb view
- [ ] Update CSS in sponsors.css.scss to new class names used in view
- [ ] Rename sponsors.css.scss to supporters.css.scss
- [ ] Update import in application.css.scss (replace sponsors)

**Additional Info**
:+1: Much appreciated :+1:

**Comment by NewtCobell** [comment]
On the supporters page, it still says 'sponsors' (just above the second horizontal divider) - should that be changed?

Edit: it's also on the chapter page in the sidebar above the logos.

**Comment by alejandraji** [comment]
Hi, can i jump on this? was it completed?

**Comment by kstack7** [comment]
@NewtCobell -- we can keep Sponsors there since we do still have Sponsors. We changed the name to "Supporters" to be more generalized than _just_ sponsors. Hope that makes sense :)

And yes, this was another not-closed-by-PR-title issue that has been completed. Sorry for the confusion!
