### ISSUE TITLE
GDI St Louis Link on Chapters page incorrect

### ISSUE THREAD

**Issue by Hyperchema** [girldevelopit/gdi-website#330]
On the main site under "chapters" the St Louis MO link sends you to:
https://www.girldevelopit.com/chapters/st-louis which does not exist.
The working url is:
https://www.girldevelopit.com/chapters/saint-louis

Thanks!

**Comment by Roenok** [comment]
Yeah, that one is my fault. Lo siento. Fixing it now.

**Comment by Roenok** [comment]
All better! Your canonical URL is now https://www.girldevelopit.com/chapters/st-louis.

**Comment by DBNess** [comment]
:raised_hands: nice catch & fix, @Hyperchema & @Roenok!! thank you! :clap: :clap:
