### ISSUE TITLE
Change link to Interest Form in Footer

### ISSUE THREAD

**Issue by GretchenLynd** [girldevelopit/gdi-website#331]
**Description**
There is a new form to replace the current form linked to the  'Help Bring Girl Develop It to Your Community' line in the footer. 

https://docs.google.com/forms/d/18vn6QF64wg8i7euJXSA4HlYWO4AlL9i04o7057-ewuQ/viewform

**Ask**
Please change link to point to the new form. 

Thanks, Gretchen

**Comment by kstack7** [comment]
How's this, @GretchenLynd : https://girl-develop-it-staging.herokuapp.com/
