### ISSUE TITLE
SUGGESTION - Include expanded/collapsed icon on accordians

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-website#343]
**Description**
On the mobile view of the [chapters page](https://girl-develop-it-staging.herokuapp.com/chapters), we have a accordian expand/collapse for each state. In #339, we added some nifty code that alerts screen reader users that those sections expand and collapse. However, there is no corresponding visual cue.

**Ask**
Add an expanded/collapsed icon to those headings to make it clear they are accordions. The UX standard seems to be a right-facing triangle for collapsed and a down-facing arrow for expanded, but UX advice welcome. We already load Font Awesome on the site, so it would make sense for the icons to come from the [Font Awesome set](http://fortawesome.github.io/Font-Awesome/3.2.1/icons/)

**To Do**
- [ ] Finalize a design
- [ ] Add dynamic icons via JavaScript
- [ ] Test on staging

**Additional Info**
Terrible 30-second mockup made in Paint:
![image](https://cloud.githubusercontent.com/assets/925963/8984733/7b8e5b36-36a1-11e5-9b5a-b29812694d5f.png)

**Comment by Roenok** [comment]
@snkahn UX advice welcome. Is there a clearer pattern for this?

**Comment by Roenok** [comment]
On reflection, arrows on the left side might be cleaner, especially on the FAQ page in #369

**Comment by snkahn** [comment]
Left is usually used if the content length is variable and potentially lengthy, so that would be appropriate here. I also think we should include a selected state with color, that will help (not literally this color, that would be terrible):

<img width="243" alt="screen shot 2015-11-07 at 5 54 10 pm" src="https://cloud.githubusercontent.com/assets/937330/11017783/a2b89020-8578-11e5-9f7d-0af647289ac9.png">

**Comment by snkahn** [comment]
not sure how I feel about this color, but do think some color will help clarify: 
<img width="336" alt="screen shot 2015-11-07 at 6 18 09 pm" src="https://cloud.githubusercontent.com/assets/937330/11017860/fc91ba4c-857b-11e5-9285-2edabeaae5f8.png">

**Comment by kstack7** [comment]
Thanks for the input, @snkahn! I see how the color background can help...maybe a lighter shade of gray? Was trying to pick out some other accent colors from the site maybe but hard to align with the pink. Hmmm.

**Comment by ghaida** [comment]
Icons on the left side cause a bit of a zig-zag effect that makes it difficult to scan down the list.
![pasted_image_11_10_15__11_17_am](https://cloud.githubusercontent.com/assets/342672/11067914/e1cf1b28-879c-11e5-9860-9a7dfd0ea8bc.png)

**Comment by ghaida** [comment]
Though there is a way around the above problem by adding a fixed margin to all list items.

**Comment by kstack7** [comment]
Woops never came back to close this :+1:
