### ISSUE TITLE
Add logos to Supporters page

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#350]
**Add attached logos to Supporters page**

Sponsors:
_Add sponsor logo & link_
![benefit logo](https://cloud.githubusercontent.com/assets/4427638/9089254/3741a1d4-3b62-11e5-9907-ca7ba2c0407a.png)
link to: http://www.boldisbeautiful.com/us

_Add sponsor logo & link_
![qualcommlogo](https://cloud.githubusercontent.com/assets/4427638/9087498/0ff8255c-3b59-11e5-99e4-24791cb15750.png)
link to: http://www.qualcomm.com

_Add sponsor logo & link_
![salesforce logo](https://cloud.githubusercontent.com/assets/4427638/9087510/24f1f078-3b59-11e5-9df8-add95a81faae.png)
link to: http://www.salesforce.com

_Add sponsor logo & link_
![ge logo](https://cloud.githubusercontent.com/assets/4427638/9087560/775860fe-3b59-11e5-9f1b-14691b78b424.png)
link to: http://www.ge.com/

_Add sponsor logo & link_
![bloc-logo-full-1000-grey](https://cloud.githubusercontent.com/assets/4427638/9088269/26651cc4-3b5d-11e5-80d5-040db6c910e9.png)
http://bloc.io

**Comment by kstack7** [comment]
@corinnepw how's this?

![screen shot 2015-08-12 at 11 35 20 pm](https://cloud.githubusercontent.com/assets/6612770/9242121/d4f4591a-414a-11e5-87be-e26ad4db6644.png)
