### ISSUE TITLE
Alphabetize chapter dropdown in admin interface

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-website#351]
**Description**
When adding a new bio or sponsor in the admin interface, users must select a chapter from a long dropdown list. This list in unordered. With 50+ chapters to choose from, it's a serious usability issue. 

**Ask**
Alphabetize the chapter list, probably by adding an ORDER BY to the relevant SQL query. 

**To Do**
- [x] Alphabetize list
- [ ] Test

**Additional Info**
Where is my chapter?
![image](https://cloud.githubusercontent.com/assets/925963/9176996/aacf9e6e-3f5c-11e5-8f6c-0109e3982388.png)

**Comment by kstack7** [comment]
This better, @Roenok? :)

Thankfully it was a quick fix --

> filter :chapter, member_label: :chapter, collection: proc { Chapter.order(:chapter) }

![screen shot 2015-08-12 at 11 46 06 pm](https://cloud.githubusercontent.com/assets/6612770/9242253/852e6414-414c-11e5-96f5-9076109ab0e0.png)

**Comment by Roenok** [comment]
It's beautiful! I know where my city is.

**Comment by kstack7** [comment]
hah I'm glad you brought this one up again because it was subtly bugging me each time I had to use it. Good idea! I'll get it pushed with a few other items soon.

**Comment by Roenok** [comment]
@kstack7 This seems to have reverted on production. Any thoughts?
![image](https://cloud.githubusercontent.com/assets/925963/9878210/8915d6fe-5b8f-11e5-9638-90f0cb1389a1.png)

**Comment by kstack7** [comment]
3, 2, 1 cache off!! 

Can anyone else recreate this? Maybe try a new browser or refresh?

![dropdown](https://cloud.githubusercontent.com/assets/6612770/9878660/d12a3de8-5b91-11e5-8620-3a047ad83a68.png)

**Comment by Roenok** [comment]
@kstack7 Seeing it both in Chrome Incognito and Firefox, which is weird. It's all database-driven, right? Browser shouldn't affect it. 

To clarify, the filters dialog is still in alphabetical order. However, when I go to add a new bio/sponsor/admin user, that dropdown is unordered

**Comment by kstack7** [comment]
OH. Geez, yes. That's a whole different scenario and clearly one that I missed! I thought you were seeing that on the filter, which resulted in my "turn it on and off" troubleshooting mindset :) I see it now. Thanks, @Roenok

**Comment by kstack7** [comment]
Going to merge this to staging since only a few of us actually see this dropdown. Most admin users can only edit against their own chapter so the dropdown isn't there at all.

**Comment by kstack7** [comment]
https://girl-develop-it-staging.herokuapp.com/admin

**Comment by kstack7** [comment]
Putting this puppy to bed!

https://github.com/girldevelopit/gdi-new-site/pull/365

Go break it now, @Roenok ;)
