### ISSUE TITLE
Add link to curriculum site on /materials

### ISSUE THREAD

**Issue by EliseWei** [girldevelopit/gdi-website#360]
To allow access to the full list of non-core offerings.

**Comment by corinnepw** [comment]
Here's the link. Should be added to the bottom of the page. 
http://girldevelopit.github.io/gdi-curriculum-site/

**Comment by copasetickid** [comment]
@corinnepw Are you staying that this link should go in the footer instead so it's site wide?

**Comment by corinnepw** [comment]
Sorry for being unclear! Not in the footer, but below the existing materials.

**Comment by scroniser** [comment]
Hey - I can take this one :)

**Comment by scroniser** [comment]
Just to further clarify, you're looking for something like this? (obv with better text and a correct image)![screen shot 2015-09-09 at 7 34 06 pm](https://cloud.githubusercontent.com/assets/9728572/9777420/cb9f5866-5729-11e5-9ff3-aefb7cedb1ee.png)

**Comment by Roenok** [comment]
No, it shouldn't have the same prominence as the completed classes. (Those
are added via the DB anyway.) Instead, it should just be a plain vanilla
text link below the block of class's.

**Comment by scroniser** [comment]
Hey all! I wasn't sure if the commit triggered a message, so I wanted to let you know that I submitted a fix. If it's not what you're looking for, I can make a change :)

**Comment by kstack7** [comment]
Thanks, @scroniser! I'm adding a screenshot of your work since this is the better discussion area: 
![screen shot 2015-09-22 at 1 18 19 am](https://cloud.githubusercontent.com/assets/6612770/10064874/99fd19ec-624b-11e5-8c30-89d65b4ae1a2.png)

Added "Non-core offerings" above the footer.

Any additional feedback from other members?

**Comment by EliseWei** [comment]
Not 100% sure what Corinne had envisioned, but it looks good to me.

**Comment by corinnepw** [comment]
Awesome — thanks all! Let's make the link title (since it contains _all_ curriculum) "All Course Material"

**Comment by saracope** [comment]
Thoughts on calling it "Additional Offerings" or "Additional Materials"?  Non-core raises a bunch of questions for me like:
What is core? How is core decided? Does non-core mean I can't use these materials? How does something go from non-core to core.

**Comment by corinnepw** [comment]
@saracope Additional Materials sounds good!

**Comment by corinnepw** [comment]
@scroniser @kstack7 it's great! Let's just call it "Additional Materials" vs "Non-core offerings"

**Comment by kstack7** [comment]
okay... @scroniser, want to do one more pull request with that text change? I notice some stacking commits, too...maybe a new request to keep things tidy?

Thanks for all the help!

**Comment by kstack7** [comment]
I used @scroniser's changes to create a new PR (#367) with "Additional Materials" and added one lil change from issue #310 as well. Thanks for your contribution, @scroniser :)

**Comment by scroniser** [comment]
Sorry - I've been mired in code for the last few weeks, so I wasn't able to get to this sooner. Next time!

**Comment by kstack7** [comment]
No worries, @scroniser, we appreciate the help!
