### ISSUE TITLE
Add the FAQ page

### ISSUE THREAD

**Issue by kstack7** [girldevelopit/gdi-website#369]
**Description**
_The GDI website needs a 'Frequently Asked Questions' page and Gretchen has a number of Q/As to use. Let's get them on the site!_

**Ask**
_Use Gretchen's FAQ doc (below) to create the FAQ page on the website._

**To Do**
- [x] Review Gretchen's FAQ doc here: https://docs.google.com/document/d/1JmiVWkbYHY5gMbzSJKzaKjY2XDiQzvF468vpzuAi1xQ/edit
- [x] Create new FAQ page on the website
- [x] Add content in an organized manner (e.g. accordion)
- [x] Upload to staging for discussion

**Comment by kstack7** [comment]
Initial attempt. Not sure if we like the accordion here ( @Roenok it's your suggested/accessible version ) or to keep them as open paragraphs like the Code of Conduct? Thoughts?

![screen shot 2015-10-18 at 5 29 12 pm](https://cloud.githubusercontent.com/assets/6612770/10566795/a18dcd1a-75be-11e5-957b-6fd3dd15a55c.png)

**Comment by Roenok** [comment]
I like the idea of the accordions; makes it easier to scan the questions quickly. I do think we should add some open/closed icons to make the accordion effect clearer (see #343)

**Comment by kstack7** [comment]
Ah yes I recall the arrow suggestions. Any more design/UX'ers want to this?

**Comment by rebeccasigo** [comment]
What about keeping the questions in a column on the left (easy to scan) and then clicking on each will scroll you to the answer? Ex: https://mixpanel.com/help/questions/ (though I'd suggest showing all Qs, not just topics on LH column like Mixpanel's help page does)

**Comment by kstack7** [comment]
I like that idea, but am a bit concerned that it's a bit much for a smaller number of questions. That design seems to work well because there are far more options to pick. Maybe a combination of interactions that keeps things on the same page?

**Comment by ghaida** [comment]
How about keeping the list of questions up top with anchor links to the answers further down the page. Each answer could have a "Back to top" shortcut to get back to the questions.

**Comment by kstack7** [comment]
Okay! I've uploaded the initial layout for the FAQ page with the original Qs from Gretchen. Let's get some eyes on it and discus some improvements. Feel free to pull down/add to it!

https://girl-develop-it-staging.herokuapp.com/faq

**Comment by kstack7** [comment]
Chevrons added to the left: 

https://girl-develop-it-staging.herokuapp.com/faq
