### ISSUE TITLE
Uncapitalize names on the About page

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-website#370]
**Description**
On the about page (https://www.girldevelopit.com/about), the names of our staff and board are in ALL CAPS. This makes them hard to read (weird kerning) and hard to copy-paste into emails.

**Ask**
Switch to title case for the names

**To Do**
- [ ] Create a h3.nocaps style
- [ ] Apply to board names
- [ ] Celebrate!

**Comment by scroniser** [comment]
sorry, just forgot to mention this issue in my recent pull request.
