### ISSUE TITLE
Reduce vertical height of mobile nav

### ISSUE THREAD

**Issue by ghaida** [girldevelopit/gdi-website#384]
**Description**
Current mobile navigation takes up too much space which forces users to scroll to get to content.

**Ask**
Let's adopt a more content-first approach and find ways to reduce the vertical height of the nav or implement an off-canvas navigation.

**To Do**
- [ ] Design a few options for nav improvements

**Additional Info**
<img width="318" alt="screen shot 2015-11-10 at 11 58 25 am" src="https://cloud.githubusercontent.com/assets/342672/11069158/b1991534-87a2-11e5-9eef-27e97570c422.png">

**Comment by Roenok** [comment]
@snkahn Any design/UX thoughts on this one? I'm hesitant to introduce an off-canvas navigation because it's hard to make them accessible.

**Comment by k80bowman** [comment]
I just did this for our chapter to solve this same problem. It's not perfect, but it's a place to start.
![screen shot 2016-10-19 at 7 41 58 pm](https://cloud.githubusercontent.com/assets/12739849/19580306/7255f728-96f3-11e6-9a73-2e5fba2b06a7.png)

**Comment by NewtCobell** [comment]
@k80bowman I like it! @ghaida and @Roenok , what do you think?
