### ISSUE TITLE
Remove two chapters from site

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#392]
**Description**
_Please remove all instances of Bucks County and Tri-Cities from website, including homepage map and individual chapter pages_

**To Do**
- [x] Remove Bucks County (PA)
- [x] Remove Tri-Cities (WA)

**Comment by Roenok** [comment]
Done! Thanks to the new dynamic city count in #389 the about page also updated. Thanks @kstack7!
