### ISSUE TITLE
Update About Page bio & headshot

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#400]
**Description**
_Update Corinne's bio and headshot on About_

**To Do**
- [ ] Add photo: 
  ![corinne warnshuis headshot](https://cloud.githubusercontent.com/assets/4427638/12225892/d5f37388-b7e1-11e5-870b-504ceba80890.jpg)
- [ ] Update bio:
  Corinne is a passionate advocate for community-centered movements and their power to change the world. Prior to becoming the first Executive Director of Girl Develop It, she co-led the organization’s Philadelphia chapter to become one of the organization's largest and most active.
  She has previously held positions with the Technical.ly news network, producing large-scale technology conferences like Philly Tech Week and Baltimore Innovation Week, and at WHYY, Philadelphia’s NPR and PBS affiliate, in community relations.
  Corinne has spoken at the White House, Dreamforce, Lesbians Who Tech Summit, Code Conf, OSCON and more.
  A native Californian, Corinne moved to Philadelphia after graduating from University of California — Santa Cruz with a degree in Sociology and Film & Digital Media.

**Comment by alohaas** [comment]
@corinnepw see PR #399

**Comment by alohaas** [comment]
![about_updates](https://cloud.githubusercontent.com/assets/4480279/12236085/c9c186e0-b845-11e5-9f10-6586bd9fad49.png)

**Comment by corinnepw** [comment]
Awesome! This looks great. I think I sent a funky size in. Just checked Vanessa's photo and matched the size to 510 x 510 (and I think it appears 219 x 219. Thank you @alohaas 
![corinne warnshuis headshot](https://cloud.githubusercontent.com/assets/4427638/12236535/6a87f68e-b848-11e5-91d7-4af5b4781f35.jpg)

**Comment by kstack7** [comment]
Yeah was going to add to make sure the pics are the same size/height so that the paragraph tops align. Nice!

**Comment by alohaas** [comment]
Whoops. Didn't even notice (bein' sloppy :crocodile:). @kstack7 @corinnnepw I'll fix that asap.

**Comment by alohaas** [comment]
@corinnepw @kstack7 should be resolved. 
![about_updates](https://cloud.githubusercontent.com/assets/4480279/12249597/b28a5ae4-b88e-11e5-810c-6acf453ddddb.png)
