### ISSUE TITLE
Add Chapter Leader Group Photo to About Page

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#422]
**Add awesome 2015 Summit group photo to About**

**Ask**
_Add this photo to About_ 
![img_1813](https://cloud.githubusercontent.com/assets/4427638/12987979/9bb55d86-d0cc-11e5-95cc-6f42d7b9386f.JPG)

**Additional Info**
_Add to Our Team section, perhaps with caption "Girl Develop It Chapter Leaders at 2015 Annual Leadership Summit"._

**Comment by lisli** [comment]
@corinnepw Where would you like this photo to go? Top of the page? Towards the bottom?

**Comment by corinnepw** [comment]
ooh! How about below our team and above the headshots?

On Fri, Jun 17, 2016 at 1:40 PM, lisli notifications@github.com wrote:

> @corinnepw https://github.com/corinnepw Where would you like this photo
> to go? Top of the page? Towards the bottom?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/girldevelopit/gdi-website/issues/422#issuecomment-226833737,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEOPdtYbRpT_gCRGRx6sw_CM7pxShi60ks5qMtv8gaJpZM4HYdyq
> .

## 

Corinne Warnshuis
Executive Director | Girl Develop It http://www.girldevelopit.com
corinne@girldevelopit.com | @corinnepw https://twitter.com/corinnepw |
831-331-1199

_Check out our upcoming classes and events on girldevelopit.com
http://girldevelopit.com._

**Comment by lisli** [comment]
@corinnepw 👍 Getting the project set up now, PR forthcoming 😸
