### ISSUE TITLE
Remove #GDIDAY section from donation page?

### ISSUE THREAD

**Issue by alohaas** [girldevelopit/gdi-website#429]
I'm not sure if this is urgent or if the #GDIDay section can persist throughout the year, but I thought I would check to see if it should be taken down. I'd be happy to remove it if necessary.

<img width="721" alt="screen shot 2016-03-18 at 9 57 50 am" src="https://cloud.githubusercontent.com/assets/4480279/13879837/e66f0270-ecef-11e5-8e25-6edd9fa694f9.png">

**Comment by corinnepw** [comment]
That would be so great @alohaas! Thank you!

**Comment by alohaas** [comment]
:metal: I will shoot for a PR on Friday.

**Comment by kstack7** [comment]
:+1:

**Comment by kstack7** [comment]
Any progress on this?

**Comment by kstack7** [comment]
@alohaas I'm going to reassign this if that's okay with you. It's getting quite outdated.

**Comment by alohaas** [comment]
@kstack7 that's okay with me. sorry i have been super slow on this one! 🐢
