### ISSUE TITLE
Grant admin access for CLs

### ISSUE THREAD

**Issue by imuchnik** [girldevelopit/gdi-website#435]
In a more active chapters with lots going on, it is somewhat unfair to place all the chapter page content update burden on just 1 person. 
So to that end, i am porposing to grant admin access to at least 1 other CL to share the load equally.
Please voice your opinions in comments.

**Comment by imuchnik** [comment]
#

**Comment by Roenok** [comment]
I'll +1 this just because most chapters like to distribute work. We do need a system in place for pruning inactive accounts, though.

**Comment by luizfnunesmarques** [comment]
This issue is still open?

Thanks :)
