### ISSUE TITLE
Remove Operations Lead job from /jobs

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#442]
Please remove the Operations Lead job description from the /jobs page

**Comment by kstack7** [comment]
I will give this a short grace period if anyone wants to take a stab at this one! Otherwise I can rip the bandaid fast :)

**Comment by corinnepw** [comment]
🙌

On Monday, April 18, 2016, Kristen notifications@github.com wrote:

> Closed #442 https://github.com/girldevelopit/gdi-new-site/issues/442
> via 147deda
> https://github.com/girldevelopit/gdi-new-site/commit/147deda6fd0f9a4662d3807c16985761cb60ca80
> .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/girldevelopit/gdi-new-site/issues/442#event-632289618

## 

Corinne Warnshuis
Executive Director | Girl Develop It http://www.girldevelopit.com
corinne@girldevelopit.com | @corinnepw https://twitter.com/corinnepw |
831-331-1199

_Check out our upcoming classes and events on girldevelopit.com
http://girldevelopit.com._
