### ISSUE TITLE
Add Nonprofit info to footer

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#449]
Can you please add the following information to the footer of the site? 

Girl Develop It, 1522 Cole Street, Enumclaw, WA, 98022, USA 
_Girl Develop It is an exempt organization as described in Section 501(c)(3) of the Internal Revenue Code. Our EIN is 46-3103695._

**Comment by kstack7** [comment]
Are the italics intentional and desired for the footer, @corinnepw?

**Comment by corinnepw** [comment]
Yep!

On Thursday, April 28, 2016, Kristen notifications@github.com wrote:

> Are the italics intentional and desired for the footer, @corinnepw
> https://github.com/corinnepw?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/girldevelopit/gdi-website/issues/449#issuecomment-215585153

## 

Corinne Warnshuis
Executive Director | Girl Develop It http://www.girldevelopit.com
corinne@girldevelopit.com | @corinnepw https://twitter.com/corinnepw |
831-331-1199

_Check out our upcoming classes and events on girldevelopit.com
http://girldevelopit.com._
