### ISSUE TITLE
SUGGESTION: Placeholder text/image for empty sponsor section

### ISSUE THREAD

**Issue by kstack7** [girldevelopit/gdi-website#466]
**Description**
_Might be helpful to draw attention to a chapter page's sponsor section if it's empty. Maybe a placeholder image or text saying "want to sponsor this chapter?" with a link to the chapter email address._

**Ask**
_Create an if-statement that will check whether to show the CTA text or list of sponsors as a result._

**To Do**
- [ ] Get approved text/content from HQ
- [ ] Add if-statement to chapters page in code
- [ ] Push to staging for discussion

**Additional Info**

The awkwardly empty sponsor section for example:

![screen shot 2016-06-25 at 2 29 18 pm](https://cloud.githubusercontent.com/assets/6612770/16358467/41111c60-3ae1-11e6-8022-6cbec3b0d479.png)

**Comment by Roenok** [comment]
@kstack7 Rochester deserves all the sponsors! I'd actually like to propose we add the "want to sponsor" link to the bottom of every chapter's list. That way, potential sponsors will always have a lead.

**Comment by kstack7** [comment]
Great point! No reason to remove it... :+1:
