### ISSUE TITLE
Add LaVonna's bio to the About page

### ISSUE THREAD

**Issue by GretchenLynd** [girldevelopit/gdi-website#468]
Please add the following bio for LaVonna:  

**
![lavonna headshot](https://cloud.githubusercontent.com/assets/8474648/16736975/94b63edc-474c-11e6-83c9-5103a0e306a7.jpg)
**
LaVonna Ricketts, Program Director
LaVonna is committed to organizations that cultivate spreading knowledge, continuous learning, and social impact. She fights to create equal career and educational opportunities for women. 
LaVonna comes from a background in education. She holds a master’s degree in Education Policy from the University of Pennsylvania, and has worked with an array of education, community, and girls' empowerment organizations, including the Philadelphia Center for Arts and Technology, Girls Prep/Public Prep, and the Girl Scouts. Most recently, LaVonna was the Director of Operations with KIPP Philadelphia Elementary Academy.
LaVonna believes her professional and personal work should always be grounded in developing programs, policies, and systems that benefit the individuals that they directly impact, as well as improve the lives and well-being of the connecting communities.

**Comment by intersim** [comment]
@GretchenLynd happy to help on this!

**Comment by Roenok** [comment]
Thanks @intersim! Looks like we'll have an odd number of profiles. Maybe center the new bio below the existing ones?

**Comment by intersim** [comment]
@Roenok Sounds good to me, I just put in a PR with a center column below the other 2 bios.

**Comment by kstack7** [comment]
Just as a follow-up, you can view the changes on staging: https://girl-develop-it-staging.herokuapp.com/about
