### ISSUE TITLE
Update ReadTheDocs to reflect Vagrant/setup changes

### ISSUE THREAD

**Issue by kstack7** [girldevelopit/gdi-website#471]
**Description**
_We now have a Vagrant script to help make development setup a breeze! We just need to mention it in our readthedocs so folks know how to use it properly._

**Ask**
_Carry temporary README instructions to ReadTheDocs!_

**To Do**
- [ ] Find README instructions
- [ ] Move to ReadTheDocs with additional details to help
- [ ] Rejoice!

**Additional Info**

(In README)

How to Vagrant
To set up the vagrant environment locally: 1. Install VirtualBox 2. install Vagrant 3. clone the git repository 4. $ vagrant up 5. $ vagrant ssh 6. $ cd /opt/gdi/development 7. $ bundle install 8. $ rake db:create db:migrate db:seed 9. $ bin/rails s 10. Point your browser to localhost:3000 11. DEVELOP IT! \o/

**Comment by billimarie** [comment]
@kstack7 This is closed with #475 👍  should we remove the Vagrant info from the readme?

**Comment by kstack7** [comment]
Ah yes! I also think @Roenok was going to add her $.02 to it as well. But we definitely want that readme info removed :) Thanks for your help, @billimarie!

**Comment by kstack7** [comment]
Removed from ReadMe :)
