### ISSUE TITLE
Add some margins to paragraphs

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-website#478]
**Description**
Our reset stylesheet gives all paragraphs a margin of zero. That means when we have blocks of text with multiple paragraphs, there is no space between them.

**Ask**
Give paragraphs a small margin, to improve readability

**To Do**
- [ ] Choose a sensible margin value
- [ ] Update CSS to include the new value
- [ ] Test across the site

**Additional Info**
Current state:
![image](https://cloud.githubusercontent.com/assets/925963/16988391/5321d83c-4e5e-11e6-8000-24da88a6ba17.png)

Proposed change:
![image](https://cloud.githubusercontent.com/assets/925963/16988472/85ceb9a8-4e5e-11e6-97ee-506c2d30df3e.png)

**Comment by intersim** [comment]
@Roenok I can help on this! Just took a look, and maybe just profile paragraphs on the about page need padding added? Looks like that's what's happening elsewhere on the site.
