### ISSUE TITLE
Update address in footer and on 'Donate' page

### ISSUE THREAD

**Issue by anythingcodes** [girldevelopit/gdi-website#485]
**Description**
The address in the footer and the [Donate page](https://www.girldevelopit.com/donate) is GDI's former Enumclaw, WA address. Need to update with the new NYC address.

**Ask**
When completed, addresses will be _Girl Develop It, 1732 1st Ave #24681, New York, NY, 10128, USA_

**To Do**
- [ ] Update address text in footer
- [ ] Update address text on [Donate page](https://www.girldevelopit.com/donate)

**Additional Info**

_Footer:_ 
![image](https://cloud.githubusercontent.com/assets/3537575/17277008/9edbad24-5706-11e6-8133-cb13ed859608.png)

_Donate page:_
![image](https://cloud.githubusercontent.com/assets/3537575/17277019/fb493a4a-5706-11e6-9fa5-4a203aa39e4c.png)

**Comment by Roenok** [comment]
Well spotted, @anythingcodes! Tagging this one beginner-friendly. Anyone want to grab it?
