### ISSUE TITLE
Add Sponsor logo to Summit Page

### ISSUE THREAD

**Issue by GretchenLynd** [girldevelopit/gdi-website#498]
Please add Fair Play sponsor logo to the Summit page. 

![fair-play-logo-light](https://cloud.githubusercontent.com/assets/8474648/18980458/ca3e18ca-8691-11e6-8b88-4522eb71acb2.png)

**Comment by kstack7** [comment]
http://fairplay.video/, right?

**Comment by GretchenLynd** [comment]
Thanks Kristen!
