### ISSUE TITLE
Revised logo for IBM for Summit Sponsor

### ISSUE THREAD

**Issue by GretchenLynd** [girldevelopit/gdi-website#508]
Maureen sent new logo to be added to the Summit sponsor page. Please replace logo sent with previous pull request. 

![ibm](https://cloud.githubusercontent.com/assets/8474648/19820656/909cb026-9d17-11e6-8d28-a699c5b5200a.jpg)

**Comment by GretchenLynd** [comment]
Pull request was #506

**Comment by mmcelaney** [comment]
Thanks @GretchenLynd :) @kstack7 once somebody pushes this logo into the repo I am happy to update my pr.

**Comment by mmcelaney** [comment]
added! thanks @kstack7
