### ISSUE TITLE
Add "get involved" tab to GDI website 

### ISSUE THREAD

**Issue by LaVonnaR** [girldevelopit/gdi-website#513]
We would like to add a "get involved" tab to the Girl Develop It website between the existing "about" and "jobs" tabs on the bottom of the site home page. When clicked on, the "get involved" page should look similar to the GDI jobs page, seen here [https://www.girldevelopit.com/jobs](url), in setup. The title should read "Join Our Community!", and the description beneath should read "Girl Develop It is excited to offer different opportunities to get involved and join our community. Take a look below to see what may be available in your area!" Below the description should be a list of open volunteer roles, the first (and currently the only) being the Chapter Leader role, like such:

Chapter Leader 

Chapter Leader should hyperlink to a page with the role description, which can be found here [https://docs.google.com/document/d/1ePSYxzCii9pjeJ9ISB9l5k1XKwhuFGZf729dJ6wOj-A/edit?usp=sharing](url). The role description should go directly onto the page, including the GDI letterhead. Below the description should read--

We are currently looking for Chapter Leaders in the following cities:
Grand Rapids, Michigan
Houston, Texas
Las Vegas, Nevada
Nashville, Tennessee
New Orleans, Louisiana
Oakland, California
Orange County, California
Portland, Oregon
San Antonio, Texas
Washington DC

Following the city list, this statement about how to contact the organization if interested--

If interested, please email a resume and brief cover letter to inquiries@girldevelopit.com, with subject GDI Chapter Leader Role-[City]. 

That's everything. Does it all make sense? Questions or concerns? We are open to suggestions!

**Comment by intersim** [comment]
I can help on this!

**Comment by kstack7** [comment]
Great, @intersim :) We're always looking for more hands on deck so that'd be lovely!

**Comment by kstack7** [comment]
@intersim is that information above enough to get a start on it? Let me know if you have questions and we can walk through it or start to flesh it out :) 👍

**Comment by kstack7** [comment]
I will work on this over the weekend.

**Comment by intersim** [comment]
Ack, sorry for being MIA.

**Comment by kstack7** [comment]
Pull request #516

**Comment by kstack7** [comment]
https://www.girldevelopit.com/get-involved :)

**Comment by DBNess** [comment]
🙌👍 thanks, @kstack7!!
