### ISSUE TITLE
Add sponsor logos to Supporters page 

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#527]
Add Twilio logo (attached below) to girldevelopit.com/supporters
![twilio org logo](https://cloud.githubusercontent.com/assets/4427638/21994957/5d4ddd4a-dbf0-11e6-9b41-b59b38308ff6.png)
Link to: https://www.twilio.org/

Add Capital One logo
![capital one logo](https://cloud.githubusercontent.com/assets/4427638/21995048/cdf7aecc-dbf0-11e6-81de-0665e14c3269.png)
Link to: https://www.capitaloneinvestingforgood.com/

Add Infosys Foundation logo
![foundationusa_logo_final copy 1](https://cloud.githubusercontent.com/assets/4427638/21995080/f8495482-dbf0-11e6-876e-2c7bc0a3367e.jpg)
Link to: http://www.infosys.org/infosys-foundation-usa/

Add Cars.com logo
![image](https://cloud.githubusercontent.com/assets/4427638/21995640/f1eefd64-dbf3-11e6-8da4-9982953d1ec3.png)
Link to: https://www.cars.com/

Add Turing School logo
![image](https://cloud.githubusercontent.com/assets/4427638/21995715/4e5969a4-dbf4-11e6-977c-2a3e4b681e4c.png)
Link to: https://www.turing.io/

**Comment by dnahol** [comment]
Fixed. Pull request coming up.

<img width="969" alt="screen shot 2017-01-31 at 6 04 27 pm" src="https://cloud.githubusercontent.com/assets/2976514/22492673/e07b9a5e-e7df-11e6-8dfd-23e4c30de038.png">

**Comment by kstack7** [comment]
Wonderful! Thank you @dnahol for the work and the added screenshot :) We appreciate it!
