### ISSUE TITLE
Modify Girl Develop It website's 'get involved' page

### ISSUE THREAD

**Issue by LaVonnaR** [girldevelopit/gdi-website#529]
We would like to make a few modifications to the website's 'get involved' page [https://www.girldevelopit.com/get-involved](url).

1. Under Chapter Leader, we have updated the role description. The updated description can be found using this link. [https://docs.google.com/document/d/1ePSYxzCii9pjeJ9ISB9l5k1XKwhuFGZf729dJ6wOj-A/edit?usp=sharing](url)

2. Currently the last sentence under the 'Lead In Your Community Section' reads "If interested, please email a resume and brief cover letter to inquiries@girldevelopit.com with subject GDI Chapter Leader Role-[City]." 

We would like to change it to read "If interested, please apply by completing our New Chapter Leader Interest Form!" 

The words "New Chapter Leader Interest Form" should link to the form itself with this link. [https://docs.google.com/a/girldevelopit.com/forms/d/e/1FAIpQLSekQYRAKq26ONeQ77a0LYQbk8znbYFN_0c2ZUj4jcwL6dOwTA/viewform](url) 

Thank you, please let us know if there are any questions!

**Comment by luizfnunesmarques** [comment]
Working on this issue.

Glad to help :)

**Comment by kstack7** [comment]
Hooray! Thank you @luizfnunesmarques  :) We appreciate it! Let us know if you have any questions...

**Comment by luizfnunesmarques** [comment]
You're welcome @kstack7 :)
