### ISSUE TITLE
Remove "Privacy Concerns" section from Code of Conduct

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#535]
**Description**
*Remove "Privacy Concerns" section and its contents from Code of Conduct. This is not something we can viably ensure in our classrooms or at our events.*

https://www.girldevelopit.com/code-of-conduct

**Comment by twhyn** [comment]
Hi, I would like to help on this. may I?

**Comment by Roenok** [comment]
@twahyuni Yes, we'd love some help!
