### ISSUE TITLE
Add (and remove) sponsor logos on Supporters page

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#537]
Add:
Docker logo to supporters page (https://www.girldevelopit.com/supporters)
![docker logo](https://cloud.githubusercontent.com/assets/4427638/25148114/bfba7dc2-2447-11e7-9d52-82286dae058d.png)

Remove:
Knight Foundation, Duck Duck Go and Sticker Mule and AOL

**Comment by kstack7** [comment]
Taking care of these so we can align with news blasts :)

**Comment by kstack7** [comment]
https://girl-develop-it-staging.herokuapp.com/about

**Comment by kstack7** [comment]
Wrong one... this one! https://girl-develop-it-staging.herokuapp.com/supporters
