### ISSUE TITLE
Remove Phoenix Chapter Leaders

### ISSUE THREAD

**Issue by Oh-KPond** [girldevelopit/gdi-website#540]
Please remove the following chapter leaders from the Phoenix Chapter page (https://www.girldevelopit.com/chapters/phoenix): 
CORALIZ DERETA 
LAURA LYNCH FREER

Thank you!!

**Comment by Roenok** [comment]
@Oh-KPond Chapter leaders can actually update their own content, no pull requests needed! I'll send you information on how to get access on Slack.
