### ISSUE TITLE
Add Chapter Program Manager to Jobs page

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#541]
**Description**
GDI is hiring a full-time Chapter Program Manager! To advertise the role and enable easy sharing among CLs and our network, we'd like to add it to our jobs pages.

**Ask**
Add Chapter Program Manager job description to girldevelopit.com/jobs

**Additional Info**
Please find all content to be added here: https://docs.google.com/document/d/1VlZEOqshH0IMjKDj_6-eVJf0ZBUwSGGSw-7ZV_c4vA8/

**Comment by kstack7** [comment]
Thanks again, @elisekain :D

**Comment by corinnepw** [comment]
👏  thank you both for the speedy action @elisekain & @kstack7!
