### ISSUE TITLE
Add DreamHost logo to Summit sponsors page

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#564]
Add DreamHost logo to girldevelopit.com/summit sponsors area

![dreamhost logo](https://user-images.githubusercontent.com/4427638/29622103-7f87a84e-87f0-11e7-8a12-aab26f6cf316.png)

**Comment by corinnepw** [comment]
Hello! See that this has been closed but don't see it on the girldevelopit.com/summit page. Looks like it was added to girldevelopit.com/supporters instead.

**Comment by kstack7** [comment]
Woops. Misread. Will fix!

**Comment by kstack7** [comment]
Actually closed now.
