### ISSUE TITLE
Add two sponsor logos

### ISSUE THREAD

**Issue by shanisebarona** [girldevelopit/gdi-website#573]
Hi! 

Please add the following two logos of our sponsors onto the [girldevelopit.com/summit](http://girldevelopit.com/summit) site!

![slack logo](https://cdn.worldvectorlogo.com/logos/slack.svg)
![revzilla logo](https://user-images.githubusercontent.com/18401275/30760586-be322928-9fa8-11e7-8a68-b3c5173b8255.PNG)

Thank you! ✨

**Comment by M0nica** [comment]
I am interested in working on this! I've TA'd with GDI-NYC Please let me know if I can contribute.

**Comment by kstack7** [comment]
Woops! Sorry, @M0nica, but we have that PR ready to launch to production tonight. BUT! We often have updates that could use some extra hands on deck if you're willing to try and spin up a local environment for yourself! You can fork the repo and use the readthedocs to try it out -- highly recommend using our vagrant setup, which simplifies the whole process (aside from some chunky downloads/installations). http://gdi-new-site.readthedocs.io/en/latest/sources/installation/#how-to-vagrant

Feel free to give me a shout if you have questions :)

**Comment by M0nica** [comment]
Thanks @kstack7 for letting me know! I am going to set up the site locally so that I can contribute in the future.

**Comment by kstack7** [comment]
A'course @M0nica --that'd be great :) Keep me posted if you hit any snarls -- hopefully smooth sailing for ya!
