### ISSUE TITLE
add sponsor to supporter page 💪

### ISSUE THREAD

**Issue by shanisebarona** [girldevelopit/gdi-website#589]
Hi again 👋 

Please add Slack to the supporter page. 

![slack_rgb 1](https://user-images.githubusercontent.com/18401275/32058161-518ea806-ba37-11e7-8736-3a392dcb8b68.png)

Thank you ✨

**Comment by joncancode** [comment]
Hi there @shanisebarona i'd love to contribute and possibly even #588 #579 and #578 but let's start here.

I'm relatively new to open source contributions so one at a time would be ideal :-)

**Comment by kstack7** [comment]
@joncancode awesome! We love having new folks learn the git/open source ropes with us :) We just merged #578 and #579, but you're more than welcome to try out #588 and this one :)

**Comment by joncancode** [comment]
@kstack7 pull request for #589 made. would love to get some feedback with the whole pull request process. thanks in advance :-)
