### ISSUE TITLE
Add Marketing role to website

### ISSUE THREAD

**Issue by shanisebarona** [girldevelopit/gdi-website#592]
Hi, happy new year! 🌟 

Please add the Director of Marketing job description to https://www.girldevelopit.com/jobs.

https://docs.google.com/document/d/1_yTIM2bSCOVRY0xRvRld8kLm2JzkaNe9bc7lW4ACO2s/edit#

Thank you!

**Comment by elisekain** [comment]
So. Excited. 😍 I'm on it.
