### ISSUE TITLE
Pull Marketing role from /jobs page

### ISSUE THREAD

**Issue by shanisebarona** [girldevelopit/gdi-website#597]
Hi there! 

Can you please remove the Marketing role from the /jobs page, tomorrow 2/16? 

Thank you! ✨

**Comment by arlemagne** [comment]
Hi there! I'm new to open source and would love to take this one if someone's not already working on it. Thanks!

Edit: I have a PR for the issue here: https://github.com/girldevelopit/gdi-website/pull/598
