### ISSUE TITLE
404 error trying to access the html-css curricula -- most recent was the slides for the Intermediate HTML/CSS http://girldevelopit.github.io/gdi-featured-html-css-intermediate/. 

### ISSUE THREAD

**Issue by evagabriela** [girldevelopit/gdi-website#609]
**Problem description:** User gets a 404 error when trying to access to html-css intermediate curricula ( from the website: https://www.girldevelopit.com/materials/inter-html)
![screencapture-girldevelopit-github-io-gdi-featured-html-css-intermediate-2018-06-20-15_28_43](https://user-images.githubusercontent.com/2048536/41687930-a98fb154-749e-11e8-870d-534b8e2d0120.png)

**Suggested solution:** Update the link in the website to use the new GDI master repo materials where for example for the html-css-intermediate materials, the website should link it to the materials inside of the html-css-intermediate folder. 

     * GDI Master Curriculum repo: https://github.com/girldevelopit/GDI-Master-Curriculum
     * html-css-intermediate materials: https://github.com/girldevelopit/GDI-Master-Curriculum/tree/master/html-css-intermediate

**Reason for the problem:**  The error is due to a change on the link which happened because of the merge of the html-css materials to the GDI master repo ( the website currently has the link to the original html-css repo and therefore the error was generated because of the subdirectory which was necessary for the merge into the GDI master repo).

**Comment by corinnepw** [comment]
cc @shanisebarona @leekinney

**Comment by kstack7** [comment]
Updated links to new repo location.

https://www.girldevelopit.com/materials/inter-html
